version: '2.1'

volumes: 
  cache:
    external: true

services: 
  test:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      # - ../../src:/application
      - cache:/cache
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      TEST_OUTPUT_DIR: /reports

  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -q -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5